update portal and syscall tests

diff --git a/tests/unit_tests/test_target/patches/tests/portal.yaml b/tests/unit_tests/test_target/patches/tests/portal.yaml
--- a/tests/unit_tests/test_target/patches/tests/portal.yaml
+++ b/tests/unit_tests/test_target/patches/tests/portal.yaml
@@ -6,17 +6,34 @@ plugins:
         type: file_contains 
         file: console.log
         string: "/tests/portal.sh PASS"
+      portal+write:
+        type: file_contains 
+        file: shared/tests/portal.sh/stdout
+        string: "portal: write_file from portal passed"
 
 static_files:
   /tests/portal.sh:
     type: inline_file
     contents: |
       #!/igloo/utils/sh
-      set -ex
+      set -x
+      set +e # ignore non-zero exit code
 
       echo "test read value" > /tmp/portal_test
 
-      /igloo/utils/send_syscall ioctl 0x0 0x89f3
+      /igloo/utils/send_syscall ioctl 0x0 0x89f3 stringval
 
+      if [ $? -ne 13 ]; then
+        echo "Error: send_syscall retval failed"
+        exit 1
+      fi
+
+      /igloo/utils/busybox cmp /tmp/write_send_syscall /igloo/utils/send_syscall
+
+      if [ $? -eq 0 ]; then
+        echo "portal: write_file from portal passed"
+      else
+        exit 1
+      fi
       exit 0
     mode: 73
diff --git a/tests/unit_tests/test_target/patches/tests/syscall.yaml b/tests/unit_tests/test_target/patches/tests/syscall.yaml
--- a/tests/unit_tests/test_target/patches/tests/syscall.yaml
+++ b/tests/unit_tests/test_target/patches/tests/syscall.yaml
@@ -41,9 +41,18 @@ static_files:
     contents: |
       #!/igloo/utils/sh
       set -x
+      set +e
+
       /igloo/utils/send_syscall ioctl 0x13 0x0 0x1
       /igloo/utils/send_syscall ioctl 0x13 0x1234 0xabce
       /igloo/utils/send_syscall ioctl 0x13 0x1234 0xabcd
+      
+      /igloo/utils/send_syscall ioctl 0x9  0xabcd 
+
+      if [$? -ne 43]; then
+        echo "Error: send_syscall retval enter failed"
+        exit 1
+      fi
       /igloo/utils/send_syscall clone 0x1338c0def2f2f3f2 0xdeadbeeff1f1f1f1 \
         0x1337c0defeedc0de 0xdeedbeeff1f1f0f2 0xdeadbeeff1f1f1f2 0x1337c0def2f2f2f2
       if [ $? -ne 42 ]; then
