Unit tests: update echoed messages in pseudofile tests clarify expected behavior

diff --git a/tests/unit_tests/configs/pseudofile_missing.yaml b/tests/unit_tests/configs/pseudofile_missing.yaml
--- a/tests/unit_tests/configs/pseudofile_missing.yaml
+++ b/tests/unit_tests/configs/pseudofile_missing.yaml
@@ -6,12 +6,11 @@ static_files:
       set -eux
 
       if [ ! -e /dev/missing ]; then
-        echo "Missing /dev/missing"
+        echo "Missing /dev/missing (expected)"
         exit 1
       fi
+      echo "FAIL /dev/misisng present when we didn't expect it to be"
 
       /igloo/utils/busybox cat /dev/missing
-
-      echo "Everything is good"
-      echo "Passed all init checks"
+      exit 1
     mode: 73
