build: handle lintly max number lines

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -21,7 +21,17 @@ jobs:
       run: pip install flake8 lintly markupsafe==2.0.1
     - name: Lint with flake8
       if: github.event_name == 'pull_request'
-      run: flake8 | lintly
+      run: |
+        set -o pipefail
+        (flake8 | lintly) 2>lintly.err || {
+          if grep -q 'diff exceeded the maximum number of lines' lintly.err; then
+            echo "Bypassing lint failure due to large diff."
+            exit 0
+          else
+            cat lintly.err
+            exit 1
+          fi
+        }
       env:
         LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
 
